name: CustomDayLength
version: '${project.version}'
main: me.equaferrous.customdaylength.CustomDayLength
api-version: 1.18
authors: [ EquaFerrous ]
description: A plugin to manually set how long the day or night lasts.
commands:
  enablecustomtime:
    description: Enables the plugin.
    usage: /<command>
  disablecustomtime:
    description: Disables the plugin.
    usage: /<command>
  setcustomtime:
    description: Sets the day/night/full-day length.
    usage: /<command> (day|night|full) <minutes>
  resetcustomtime:
    description: Resets custom lengths to default.
    usage: /<command>
