name: CustomDayLength
version: '${project.version}'
main: me.equaferrous.customdaylength.CustomDayLength
api-version: 1.18
authors: [ EquaFerrous ]
description: A plugin to manually set how long the day or night lasts.
commands:
  enablecustomtime:
    description: Your description
    usage: /<command>
  disablecustomtime:
    description: Your description
    usage: /<command>
  setcustomtime:
    description: Your description
    usage: /<command> <day/night/full> <value>
  resetcustomtime:
    description: Your description
    usage: /<command>
